### ISSUE TITLE
Bug affichage du mot de passe en clair ou non

### ISSUE THREAD

**Issue by fraucred** [Viseo/i-learning#10]
On doit laisser les mots de passe en clair, en attendant la modification de la librairie d'Henri

![bug hide-show password 1](https://cloud.githubusercontent.com/assets/13098519/24209304/2bf9029c-0f26-11e7-92ce-9c78217075c7.png)
![bug hide-show password 2](https://cloud.githubusercontent.com/assets/13098519/24209307/2e9baa7c-0f26-11e7-8f5d-75f6887f65c7.png)
![bug hide-show password 3](https://cloud.githubusercontent.com/assets/13098519/24209309/2eb18d10-0f26-11e7-990e-349339301b7b.png)
![bug hide-show password 4](https://cloud.githubusercontent.com/assets/13098519/24209310/2ebbf566-0f26-11e7-914a-0cd11a99e4c7.png)
![bug hide-show password 5](https://cloud.githubusercontent.com/assets/13098519/24209311/2ebd10e0-0f26-11e7-8796-89b4fec5ffbd.png)
![bug hide-show password 6](https://cloud.githubusercontent.com/assets/13098519/24209312/2ebd51c2-0f26-11e7-9d94-409093c26279.png)

**Comment by julidon** [comment]
c'est en clair, en ce moment. Je suis en train de rajouter un polyfill sur la librairie pour pouvoir mettre les étoiles à la place du mot de passe
