### ISSUE TITLE
Erreur sur les numéro des Quizz

### ISSUE THREAD

**Issue by PaulDennetiere** [Viseo/i-learning#2]
Quand on crée un quizz et qu'on le supprime, le quizz suivant arrive avec un numéro incrémenté. 

![issuequizz](https://cloud.githubusercontent.com/assets/17859158/23697800/7330bc4c-03e9-11e7-987c-896560283d2f.PNG)

**Comment by QDebesson** [comment]
C'était un comportement demandé l'an dernier.

________________________________
De : PaulDennetiere <notifications@github.com>
Envoyé : mercredi 8 mars 2017 10:24:58
À : Viseo/i-learning
Cc : Subscribed
Objet : [Viseo/i-learning] Erreur sur les numéro des Quizz (#2)


Quand on crée un quizz et qu'on le supprime, le quizz suivant arrive avec un numéro incrémenté.

[issuequizz]<https://cloud.githubusercontent.com/assets/17859158/23697800/7330bc4c-03e9-11e7-987c-896560283d2f.PNG>

**Comment by PaulDennetiere** [comment]
Donc je ferme.
